firs pull request
RoyNyaga/building_with_responsive_designs pull request #1
Opened 2019-07-30 16:24 UTC by RoyNyaga

We purposely left comments in the css file for easy review, if the the project is accepted we will remove them.

2019-07-30 17:10 UTC, mosaaleb commented
Reviewing

2019-07-30 17:56 UTC, mosaaleb requested changes
### Impressive @RoyNyaga, @R4Ajeti :clap:

#### The UI is clean. Your code base is very well structured and have semantic tags as recommended. Still there are some requirements needs be met before moving on.


#### Nav Bar:

- [ ] Logo alone shouldn't take the full width of the page. The Nav Bar should display the TNW logo at the leftmost part of it.

![Screenshot from 2019-07-30 19-26-07](https://user-images.githubusercontent.com/4246637/62151139-f21e7e00-b2ff-11e9-8159-3519d892c719.png)
----

- [ ] It should use fixed positioning.
- [ ] The Hamburger (bars) icon should not appear on screens bigger than mobile.

![Screenshot from 2019-07-30 19-51-41](https://user-images.githubusercontent.com/4246637/62152754-78888f00-b303-11e9-88fc-e453d677ec6d.png)


#### Latest News section:
- [ ] Each article should have an image on the leftmost part of the article and its title on the right side -- the image should be used as image tag. [Why?](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) 


#### Latest Funcing section:
- [ ] It should have three articles, each one wrapped around a pair of `<article>` -- you have already a div, let's just replace each div with `<section>` tag.

#### From Apps until Distract sections:
- [ ] It should have eight articles, each one wrapped around a pair of `<article>` -- Also you have already done this but inside `<li>` element, let's change it to `<article>` for more semantic tags.
- [ ] Let's rename also the sections as seen on TNW page -- All the section that you have is "Apps".

#### Latest Deals section:
- [ ] Let's rename the last section before footer from "Latest News" to "Latest Deals".


#### General:
- [ ] Let's add [stickler](https://github.com/microverseinc/linters-config/tree/master/css) to make sure that we have good styling guidelines.

- [ ] Let's add the readme file with the it's relevent information.


Please handle these requirements and submit a new code review.

#### Happy coding :computer:

2019-07-30 19:49 UTC, RoyNyaga commented
greetings sir, you reviewed my project
https://github.com/RoyNyaga/building_with_responsive_designs/pull/1 .
Thanks for responding this early for the review. I will like us to talk a
little bit about some points you raised. I tried reaching you on slack but
so many people are called Muhammad so i don't know which, please text me on
slack lets talk about my worries.


On Tue, Jul 30, 2019 at 6:56 PM Muhammad <notifications@github.com> wrote:

> *@mosaaleb* requested changes on this pull request.
> Impressive @RoyNyaga <https://github.com/RoyNyaga>, @R4Ajeti
> <https://github.com/R4Ajeti> 👏 The UI is clean. Your code base is very
> well structured and have semantic tags as recommended. Still there are some
> requirements needs be met before moving on. Nav Bar:
>
>    - Logo alone shouldn't take the full width of the page. The Nav Bar
>    should display the TNW logo at the leftmost part of it.
>
> [image: Screenshot from 2019-07-30 19-26-07]
> <https://user-images.githubusercontent.com/4246637/62151139-f21e7e00-b2ff-11e9-8159-3519d892c719.png>
>
>    - It should use fixed positioning.
>    - The Hamburger (bars) icon should not appear on screens bigger than
>    medium.
>
> [image: Screenshot from 2019-07-30 19-51-41]
> <https://user-images.githubusercontent.com/4246637/62152754-78888f00-b303-11e9-88fc-e453d677ec6d.png>
> Latest News section:
>
>    - Each article should have an image on the leftmost part of the
>    article and its title on the right side -- the image should be used as
>    image tag. Why?
>    <https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image>
>
> Latest Funcing section:
>
>    - It should have three articles, each one wrapped around a pair of
>    <article> -- you have already a div, let's just replace each div with
>    <section> tag.
>
> From Apps until Distract sections:
>
>    - It should have eight articles, each one wrapped around a pair of
>    <article> -- Also you have already done this but inside <li> element,
>    let's change it to <article> for more semantic tags.
>    - Let's rename also the sections as seen on TNW page -- All the
>    section that you have is "Apps".
>
> Latest Deals section:
>
>    - Let's rename the last section before footer from "Latest News" to
>    "Latest Deals".
>
> General:
>
>    -
>
>    Let's add stickler
>    <https://github.com/microverseinc/linters-config/tree/master/css> to
>    make sure that we have good styling guidelines.
>    -
>
>    Let's add the readme file with the it's relevent information.
>
> Please handle these requirements and submit a new code review.
> Happy coding 💻
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1?email_source=notifications&email_token=ALZGFHLAA7TWDT7FLEUWQULQCB6FPA5CNFSM4IH6D4XKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCAA7Z5I#pullrequestreview-268565749>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZGFHMTRYOFROMUX5VHBATQCB6FPANCNFSM4IH6D4XA>
> .
>

2019-07-31 00:33 UTC, bolah2009 commented
Currently under review

2019-07-31 00:58 UTC, bolah2009 approved these changes
## Nice Job Team :clap:

The [clone](https://raw.githack.com/RoyNyaga/building_with_responsive_designs/project_layout/index.html) looks good to me and is responsive. :+1: 


#### Check out the comment below and [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FRoyNyaga%2Fbuilding_with_responsive_designs%2Fproject_layout%2Findex.html) on using an heading (h1-h6) element in an `<article>` and `<section>` elelment. Consider checking them out before merging.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                                <li style="color: #555;">$39</li>
`SUGGESTION`

Avoid using in-line styles as much as possible. You can style this in your stylesheet.

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle<
`SUGGESTION`

Avoid using in-line styles as much as possible. You can style this in your stylesheet.

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                            Insights<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
`SUGGESTION`

Avoid using in-line styles as much as possible. You can style this in your stylesheet.

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                            Creative<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
`SUGGESTION`

Avoid using in-line styles as much as possible. You can style this in your stylesheet.

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                            Apps<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
`SUGGESTION`

Avoid using in-line styles as much as possible. You can style this in your stylesheet.

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                    <div style="display: none;" id="displaced-div">
Why did you have hidden `div` here :thinking: ?

2019-07-31 00:58 UTC, bolah2009 commented on index.html
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle<
`SUGGESTION`

Consider adding a margin to the sides of this section and implement the positioning of the `% off` section as shown below:

|Current|Preffered|
| :-----: | :------: |
| ![lastest deal current](https://user-images.githubusercontent.com/36057474/62175608-30369480-b336-11e9-8379-1110acc9152e.png)  | ![lastest deal preffred](https://user-images.githubusercontent.com/36057474/62175617-37f63900-b336-11e9-816c-a7a370407073.png) |

2019-07-31 14:08 UTC, RoyNyaga commented
Thanks sir will do that before merging


On Wed, Jul 31, 2019 at 1:58 AM BOLA AHMED BUARI <notifications@github.com>
wrote:

> *@bolah2009* approved this pull request.
> Nice Job Team 👏
>
> The clone
> <https://raw.githack.com/RoyNyaga/building_with_responsive_designs/project_layout/index.html>
> looks good to me and is responsive. 👍
> Check out the comment below and these errors
> <https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FRoyNyaga%2Fbuilding_with_responsive_designs%2Fproject_layout%2Findex.html>
> on using an heading (h1-h6) element in an <article> and <section>
> elelment. Consider checking them out before merging.
>
> Good luck with your next project. 🌟
>
> Cheers
> Bola <https://bolabuari.com/>
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r308999553>
> :
>
> > +                    <article class="grid-five-primary-list">
>
> +                        <section class="grid-five-inner-grid">
>
> +                            <a href="#" class="grid-five-picture"></a>
>
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle</a></h4>
>
> +                            <ul class="grid-five-secondary-list">
>
> +                                <li style="text-decoration: line-through; color:#aaa;">$2843.91</li>
>
> +                                <li style="color: #555;">$39</li>
>
> +                            </ul>
>
> +                        </section>
>
> +
>
> +                        <section class="grid-five-inner-grid">
>
> +                            <a href="#" class="grid-five-picture"></a>
>
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle</a></h4>
>
> +                            <ul class="grid-five-secondary-list">
>
> +                                <li style="text-decoration: line-through; color:#aaa;">$2843.91</li>
>
> +                                <li style="color: #555;">$39</li>
>
>
> SUGGESTION
>
> Avoid using in-line styles as much as possible. You can style this in your
> stylesheet.
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r308999592>
> :
>
> > +                                <li style="color: #555;">$39</li>
>
> +                            </ul>
>
> +                        </section>
>
> +
>
> +                        <section class="grid-five-inner-grid">
>
> +                            <a href="#" class="grid-five-picture"></a>
>
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle</a></h4>
>
> +                            <ul class="grid-five-secondary-list">
>
> +                                <li style="text-decoration: line-through; color:#aaa;">$2843.91</li>
>
> +                                <li style="color: #555;">$39</li>
>
> +                            </ul>
>
> +                        </section>
>
> +
>
> +                        <section class="grid-five-inner-grid">
>
> +                            <a href="#" class="grid-five-picture"></a>
>
> +                            <h4 class="grid-five-header-four"><a href="#">The Ultimate Cisco Networking Expert Certification Training Bundle<
>
>
> SUGGESTION
>
> Avoid using in-line styles as much as possible. You can style this in your
> stylesheet.
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r308999733>
> :
>
> > +                                </a>
>
> +                            </h4>
>
> +                        </li>
>
> +                        <li class="section-four-normal-list">
>
> +                            <h4>
>
> +                                <a class="section-four-normal-list-link" href="#">
>
> +                                    An introvert's guide to professional networking
>
> +                                </a>
>
> +                            </h4>
>
> +                        </li>
>
> +                    </ul>
>
> +                </article>
>
> +                <article class="section-direct-child">
>
> +                    <h2 class="section-four-main-heading">
>
> +                        <a href="#">
>
> +                            Insights<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
>
>
> SUGGESTION
>
> Avoid using in-line styles as much as possible. You can style this in your
> stylesheet.
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r308999795>
> :
>
> > -                        <img class="grid-three-content-div-image" alt="missing image" src="photos/2e76059785eea074440a624e8d79013df0a69453.png">
>
> -                        <h4 class="grid-three-content-header-four-first">SubjectWell</h4>
>
> -                        <div>
>
> -                            <h4 class="grid-three-content-header-four-second">$10M</h4>
>
> -                            <h5 class="grid-three-content-header-five">series a</h5>
>
> -                        </div>
>
> -                    </a>
>
> -                    <div class="grid-three-content-div-main-div">
>
> -                        <a class="grid-three-content-main-div-link" href="#">
>
> -                             <i class="fas fa-tag"></i>
>
> -                            <span>Pharmaceuticals, +2</span>
>
> +                </article>
>
> +                <article class="section-direct-child">
>
> +                    <h2 class="section-four-main-heading">
>
> +                        <a href="#">
>
> +                            Creative<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
>
>
> SUGGESTION
>
> Avoid using in-line styles as much as possible. You can style this in your
> stylesheet.
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r308999855>
> :
>
> > +                                SubjectWell nabs mln Series A
>
> +                                <span> on PE Hub</span>
>
> +                                </a>
>
> +                            </li>
>
> +                        </ul>
>
> +                    </section>
>
> +
>
> +                </article>
>
> +            </section>
>
> +
>
> +            <section id="section-four">
>
> +                <h2 style="display: none;">slkjdf</h2>
>
> +                <article class="section-direct-child">
>
> +                    <h2 class="section-four-main-heading">
>
> +                        <a href="#">
>
> +                            Apps<i style="position: relative; left: 5px; top: 2px;" class="fas fa-angle-right"></i>
>
>
> SUGGESTION
>
> Avoid using in-line styles as much as possible. You can style this in your
> stylesheet.
> ------------------------------
>
> In index.html
> <https://github.com/RoyNyaga/building_with_responsive_designs/pull/1#discussion_r309000111>
> :
>
> > -                </header>
>
> -            </article>
>
> -            <article id="grid-one-div-three">
>
> -                <header class="grid-one-header">
>
> -                    <div class="grid-one-header-content">
>
> -                        <h5 class="grid-one-heading">insight</h5>
>
> -                        <h2 class="grid-one-small-heading" id="grid-one-biggest-heading3">Silk orad side admin extradicted to us hit with 78 months prison sentence</h2>
>
> -                        <ul class="grid-one-list">
>
> -                            <li><a href="#">By Yessi Bello</a></li>
>
> -                            <li><a href="#"> 5 hours ago</a></li>
>
> -                            <li><a href="#">share 0</a></li>
>
> - [...]

2019-08-12 02:39 UTC, merged